clips_manager:
  ros__parameters:
    environments: ["labcegor"]
    labcegor:
      plugins: ["executive", "ros_msgs", "files"]
      log_clips_to_file: true
      watch: ["facts", "rules"]

    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10
    ros_msgs:
      plugin: "cx::RosMsgsPlugin"
    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["labcegor_bringup"]
      load: [
        "clips/labcegor_bringup/main.clp"]
